name: OpenAPI Workflow

on: [push, workflow_dispatch]

env:
  OPENAPI_MODEL_PACKAGE: boids
  OPENAPI_PACKAGE_NAME: boidsapi

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    outputs:
      openapi_files_exist: ${{ steps.openapi_files.outputs.files_exists }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check file existence
        id: openapi_files
        uses: andstor/file-existence-action@v2
        with:
          files: openapi.yaml

      - name: File exists
        run: echo ${{ steps.openapi_files.outputs.files_exists }}

  generate-angular-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI TypeScript client
    needs: prerequisites
    if: needs.prerequisites.outputs.openapi_files_exist == 'true'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate OpenAPI TypeScript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-angular
          openapi-file: openapi.yaml
          command-args: >-
            --model-package ${{ env.OPENAPI_MODEL_PACKAGE }}
            --package-name ${{ env.OPENAPI_PACKAGE_NAME }}

  generate-python-flask-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI Python Flask client
    needs: prerequisites
    if: needs.prerequisites.outputs.openapi_files_exist == 'true'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate OpenAPI Python Flask Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python-flask
          openapi-file: openapi.yaml
          command-args: >-
            --model-package ${{ env.OPENAPI_MODEL_PACKAGE }}
            --package-name ${{ env.OPENAPI_PACKAGE_NAME }}
