name: OpenAPI Workflow

on: [push, workflow_dispatch]

env:
  OPENAPI_MODEL_PACKAGE: boids
  OPENAPI_PACKAGE_NAME: boidsapi

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    outputs:
      openapi_files_exist: ${{ steps.openapi_files.outputs.files_exists }}
      authors: ${{ steps.list_authors.outputs.authors }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git-extras
          version: 1.0

      - name: Check file existence
        id: openapi_files
        uses: andstor/file-existence-action@v2
        with:
          files: openapi.yaml

  generate-angular-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI TypeScript client
    needs: prerequisites
    if: needs.prerequisites.outputs.openapi_files_exist == 'true'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate OpenAPI TypeScript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-angular
          openapi-file: openapi.yaml
          command-args: >-
            --model-package ${{ env.OPENAPI_MODEL_PACKAGE }}
            --package-name ${{ env.OPENAPI_PACKAGE_NAME }}

      - name: Generate NPM package configuration
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .package.json.j2
          output_file: typescript-angular-client/package.json
          strict: true
          variables: |
            project_version=${{ github.ref }}

      - name: Show package configuration
        run: cat typescript-angular/package.json

  generate-python-flask-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI Python Flask client
    needs: prerequisites
    if: needs.prerequisites.outputs.openapi_files_exist == 'true'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate OpenAPI Python Flask Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python-flask
          openapi-file: openapi.yaml
          command-args: >-
            --model-package ${{ env.OPENAPI_MODEL_PACKAGE }}
            --package-name ${{ env.OPENAPI_PACKAGE_NAME }}

      - name: Generate NPM package configuration
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .pyproject.toml.j2
          output_file: python-flask-client/pyproject.toml
          strict: true
          variables: |
            project_version=${{ github.ref }}

      - name: Show package configuration
        run: cat python-flask/pyproject.toml
