name: OpenAPI main workflow

on: [push, workflow_dispatch]

jobs:

  ref-openapi:
    uses: ./.github/workflows/openapi.workflow.yml
    with:
      publish: ${{ startsWith( github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '[test ci]') }}
      model_package: boids
      package_name: boids_api
    secrets:
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
