name: OpenAPI main workflow

on: [push, workflow_dispatch]

jobs:

  ref-openapi:
    uses: ./.github/workflows/openapi.workflow.yml
    with:
      publish: true
      model_package: boids
      package_name: boids_api
    secrets:
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
